### PR TITLE
Intro

### PR DESCRIPTION
**Pull request by shishkin**
Working on #4. Please give feedback.

The intention here is to give a walkthrough through this tutorial with some explanation and slides first and then let the participants repeat this tutorial on their own, so that they can learn by doing.

### CODE REVIEW

**Comment by shishkin** [comment]
Folks, I think I'm done with this one. Please give feedback.

**Comment by hhandoko** [comment]
Overall I think it's a very good example for a quick intro to Scala, we are able to cover various topics in the one code example. While I have some suggestions, rather than making further changes to this PR, I think it's better to accept and merge this and raise another PR:

1. I think the syntax and keyword breakdown / explanation can be expanded, adding a bit more explanation (e.g. comparing it to Java or other langs) can make it more relevant.
1. The jump to `Decomplecting Function` code from the preceding section seems too far. Perhaps we need to add some intermediary step(s) to make it easier for beginners.
1. I would also add a section in the beginning (or as we go along) on the Scala syntax styles, as the flexibility (e.g. `{ ... }` vs `( ... )`, parameter groups, and infix-style) can be confusing.

Thoughts?

**Review by hhandoko — APPROVED** [review]
LGTM to merge, I have some suggestions which may be better to be added in a follow-up PR (see previous comment).

**Comment by damien-neveu** [comment]
Great intro indeed, the travel from imperative to functional is very well explained.
@hhandoko I agree with your point 3, but less with the first 2 : although this intro is great, I feel it's already heavy on text and needs lengthy/focused reading. Any more explanation may make it harder to digest ? I'm assuming it'll be a presentation with a few of us in the room to answer more detailed questions.
@shishkin I have no problem with the content but I'm curious about the format : you say the intent is to `give a walkthrough through this tutorial with some explanation and slides first and then let the participants repeat this tutorial on their own`. But is it meant for them to repeat during the workshop or after it, at their own convenience ?
Shall the next part be to create slides based on this intro ? Each slide could show a newly implemented function and have notes about the scala syntax. The "travel" explanation could be the verbal presentation.

Then we need to decide what the following modules will be about : how about independent modules about different aspects of the language (e.g. _Arrays_, _Maps and Tuples_, _Collections_, _Classes_, _Pattern Matching with Case Classes_...etc). Each module could be an independent presentation with a code-base/test-suite. Or each module could build onto the previous one to complete a bigger project, say a REST API ?

**Review by damien-neveu — APPROVED** [review]

**Comment by shishkin** [comment]
Thanks @hhandoko and @damien-neveu!

I agree on follow up PRs. So I'll merge this one and we can proceed from there.

The weight of the text is a hard balance to strike. My intention was to provide more explanation while presenting, so yes, the next step would be to prepare the slides. I also intended the participants to self-study the tutorial under mentors' guidance onsite so that they can internalize the material at their own pace.

**Comment by shishkin** [comment]
On additional Scala syntax, what do you think if we provide a separate cheatsheet or a link to one to keep the tutorial shorter?

**Comment by shishkin** [comment]
I've created a separate issue #6  to dicuss additional modules.

**Comment by hhandoko** [comment]
@damien-neveu those are good points... I think what we can do instead is expand the objectives with specific details in point form (such as 'concepts to learn'), and / or add some instructors' guide markdown comments (which can be used for the slides as well).

Once we have written some other modules or a cheatsheet, we can simply link them to make it easy to navigate.

**Pull request merged**
